 #find_package ( OpenGL REQUIRED )
 set ( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DPOSIX  -DNDEBUG -DHAVE_MEMMOVE -DVIDEO_WAYLAND=OFF" )
 set ( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -DPOSIX -DVIDEO_WAYLAND=OFF" )
